# CRUD permission constants for each model

# User
PERMISSION_CREATE_USER = "create_user"
PERMISSION_READ_USER = "read_user"
PERMISSION_UPDATE_USER = "update_user"
PERMISSION_DELETE_USER = "delete_user"

# Role
PERMISSION_CREATE_ROLE = "create_role"
PERMISSION_READ_ROLE = "read_role"
PERMISSION_UPDATE_ROLE = "update_role"
PERMISSION_DELETE_ROLE = "delete_role"

# Class
PERMISSION_CREATE_CLASS = "create_class"
PERMISSION_READ_CLASS = "read_class"
PERMISSION_UPDATE_CLASS = "update_class"
PERMISSION_DELETE_CLASS = "delete_class"

# Company
PERMISSION_CREATE_COMPANY = "create_company"
PERMISSION_READ_COMPANY = "read_company"
PERMISSION_UPDATE_COMPANY = "update_company"
PERMISSION_DELETE_COMPANY = "delete_company"

# Exhibition
PERMISSION_CREATE_EXHIBITION = "create_exhibition"
PERMISSION_READ_EXHIBITION = "read_exhibition"
PERMISSION_UPDATE_EXHIBITION = "update_exhibition"
PERMISSION_DELETE_EXHIBITION = "delete_exhibition"

# Knowledge
PERMISSION_CREATE_KNOWLEDGE = "create_knowledge"
PERMISSION_READ_KNOWLEDGE = "read_knowledge"
PERMISSION_UPDATE_KNOWLEDGE = "update_knowledge"
PERMISSION_DELETE_KNOWLEDGE = "delete_knowledge"

# Project
PERMISSION_CREATE_PROJECT = "create_project"
PERMISSION_READ_PROJECT = "read_project"
PERMISSION_UPDATE_PROJECT = "update_project"
PERMISSION_DELETE_PROJECT = "delete_project"

# Review
PERMISSION_CREATE_REVIEW = "create_review"
PERMISSION_READ_REVIEW = "read_review"
PERMISSION_UPDATE_REVIEW = "update_review"
PERMISSION_DELETE_REVIEW = "delete_review"

ALL_PERMISSIONS = {
    PERMISSION_CREATE_USER,
    PERMISSION_READ_USER,
    PERMISSION_UPDATE_USER,
    PERMISSION_DELETE_USER,
    PERMISSION_CREATE_ROLE,
    PERMISSION_READ_ROLE,
    PERMISSION_UPDATE_ROLE,
    PERMISSION_DELETE_ROLE,
    PERMISSION_CREATE_CLASS,
    PERMISSION_READ_CLASS,
    PERMISSION_UPDATE_CLASS,
    PERMISSION_DELETE_CLASS,
    PERMISSION_CREATE_COMPANY,
    PERMISSION_READ_COMPANY,
    PERMISSION_UPDATE_COMPANY,
    PERMISSION_DELETE_COMPANY,
    PERMISSION_CREATE_EXHIBITION,
    PERMISSION_READ_EXHIBITION,
    PERMISSION_UPDATE_EXHIBITION,
    PERMISSION_DELETE_EXHIBITION,
    PERMISSION_CREATE_KNOWLEDGE,
    PERMISSION_READ_KNOWLEDGE,
    PERMISSION_UPDATE_KNOWLEDGE,
    PERMISSION_DELETE_KNOWLEDGE,
    PERMISSION_CREATE_PROJECT,
    PERMISSION_READ_PROJECT,
    PERMISSION_UPDATE_PROJECT,
    PERMISSION_DELETE_PROJECT,
    PERMISSION_CREATE_REVIEW,
    PERMISSION_READ_REVIEW,
    PERMISSION_UPDATE_REVIEW,
    PERMISSION_DELETE_REVIEW,
}

def is_valid_permission(permission) -> bool:
    """Check if the given permission string or list of strings is valid."""
    if isinstance(permission, str):
        return permission in ALL_PERMISSIONS
    if isinstance(permission, list):
        return all(p in ALL_PERMISSIONS for p in permission)
    return False